import { Geist, Geist_Mono } from "next/font/google";
import { Chilanka, Anta, Cookie, Autour_One, Numans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chilanka = Chilanka({
  weight: '400',
  variable: "--font-chilanka",
  subsets: ["latin"]
})

const anta = Anta({
  weight: '400',
  variable: "--font-anta",
  subsets: ["latin"]
})

const cookie = Cookie({
  weight: '400',
  variable: '--font-cookie',
  subsets: ['latin']
})

const autourOne = Autour_One({
  weight: '400',
  variable: "--font-autourOne",
  subsets: ['latin']
})

const numans = Numans({
  weight: '400',
  variable: "--font-numans",
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${chilanka.variable} ${anta.variable} ${cookie.variable} ${autourOne.variable} ${numans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
